// @generated by protoc-gen-connect-web v0.7.0 with parameter "target=ts"
// @generated from file proto/contacts/v1/contacts.proto (package proto.contacts.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateContactRequest, CreateContactResponse, DeleteContactRequest, GetContactRequest, GetContactResponse, ListContactsRequest, ListContactsResponse, UpdateContactRequest, UpdateContactResponse } from "./contacts_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * An API for managing a collection of contacts.
 *
 * @generated from service proto.contacts.v1.ContactsService
 */
export const ContactsService = {
  typeName: "proto.contacts.v1.ContactsService",
  methods: {
    /**
     * List all available contacts.
     *
     * @generated from rpc proto.contacts.v1.ContactsService.ListContacts
     */
    listContacts: {
      name: "ListContacts",
      I: ListContactsRequest,
      O: ListContactsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves a specific contact.
     *
     * @generated from rpc proto.contacts.v1.ContactsService.GetContact
     */
    getContact: {
      name: "GetContact",
      I: GetContactRequest,
      O: GetContactResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates a contact with the provided information.
     *
     * @generated from rpc proto.contacts.v1.ContactsService.UpdateContact
     */
    updateContact: {
      name: "UpdateContact",
      I: UpdateContactRequest,
      O: UpdateContactResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Deletes a contact with the provided id.
     *
     * @generated from rpc proto.contacts.v1.ContactsService.DeleteContact
     */
    deleteContact: {
      name: "DeleteContact",
      I: DeleteContactRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * Creates a contact.
     *
     * @generated from rpc proto.contacts.v1.ContactsService.CreateContact
     */
    createContact: {
      name: "CreateContact",
      I: CreateContactRequest,
      O: CreateContactResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

