// @generated by protoc-gen-connect-web v0.7.0 with parameter "target=ts"
// @generated from file proto/contacts/v1/contacts.proto (package proto.contacts.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetContactRequest, GetContactResponse, ListContactsRequest, ListContactsResponse, UpdateContactRequest, UpdateContactResponse } from "./contacts_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service proto.contacts.v1.ContactsService
 */
export const ContactsService = {
  typeName: "proto.contacts.v1.ContactsService",
  methods: {
    /**
     * @generated from rpc proto.contacts.v1.ContactsService.ListContacts
     */
    listContacts: {
      name: "ListContacts",
      I: ListContactsRequest,
      O: ListContactsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.contacts.v1.ContactsService.GetContact
     */
    getContact: {
      name: "GetContact",
      I: GetContactRequest,
      O: GetContactResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.contacts.v1.ContactsService.UpdateContact
     */
    updateContact: {
      name: "UpdateContact",
      I: UpdateContactRequest,
      O: UpdateContactResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

