version: '3'
services:
  envoy:
    image: envoyproxy/envoy-dev:c7c462fa4c10b7a71edd57ab2029619e752f4b2b
    network_mode: "host"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./contacts.pb:/tmp/envoy/contacts.pb