// @generated by protobuf-ts 2.8.2 with parameter generate_dependencies,long_type_string,server_grpc1,client_grpc1
// @generated from protobuf file "proto/contacts/v1/contacts.proto" (package "proto.contacts.v1", syntax proto3)
// tslint:disable
import { ContactsService } from "./contacts";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { CreateContactResponse } from "./contacts";
import type { CreateContactRequest } from "./contacts";
import type { Empty } from "../../../google/protobuf/empty";
import type { DeleteContactRequest } from "./contacts";
import type { UpdateContactResponse } from "./contacts";
import type { UpdateContactRequest } from "./contacts";
import type { GetContactResponse } from "./contacts";
import type { GetContactRequest } from "./contacts";
import type { ListContactsResponse } from "./contacts";
import type { ListContactsRequest } from "./contacts";
import * as grpc from "@grpc/grpc-js";
/**
 * An API for managing a collection of contacts.
 *
 * @generated from protobuf service proto.contacts.v1.ContactsService
 */
export interface IContactsServiceClient {
    /**
     * List all available contacts.
     *
     * @generated from protobuf rpc: ListContacts(proto.contacts.v1.ListContactsRequest) returns (proto.contacts.v1.ListContactsResponse);
     */
    listContacts(input: ListContactsRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: ListContactsResponse) => void): grpc.ClientUnaryCall;
    listContacts(input: ListContactsRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: ListContactsResponse) => void): grpc.ClientUnaryCall;
    listContacts(input: ListContactsRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: ListContactsResponse) => void): grpc.ClientUnaryCall;
    listContacts(input: ListContactsRequest, callback: (err: grpc.ServiceError | null, value?: ListContactsResponse) => void): grpc.ClientUnaryCall;
    /**
     * Retrieves a specific contact.
     *
     * @generated from protobuf rpc: GetContact(proto.contacts.v1.GetContactRequest) returns (proto.contacts.v1.GetContactResponse);
     */
    getContact(input: GetContactRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetContactResponse) => void): grpc.ClientUnaryCall;
    getContact(input: GetContactRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GetContactResponse) => void): grpc.ClientUnaryCall;
    getContact(input: GetContactRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetContactResponse) => void): grpc.ClientUnaryCall;
    getContact(input: GetContactRequest, callback: (err: grpc.ServiceError | null, value?: GetContactResponse) => void): grpc.ClientUnaryCall;
    /**
     * Updates a contact with the provided information.
     *
     * @generated from protobuf rpc: UpdateContact(proto.contacts.v1.UpdateContactRequest) returns (proto.contacts.v1.UpdateContactResponse);
     */
    updateContact(input: UpdateContactRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: UpdateContactResponse) => void): grpc.ClientUnaryCall;
    updateContact(input: UpdateContactRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: UpdateContactResponse) => void): grpc.ClientUnaryCall;
    updateContact(input: UpdateContactRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: UpdateContactResponse) => void): grpc.ClientUnaryCall;
    updateContact(input: UpdateContactRequest, callback: (err: grpc.ServiceError | null, value?: UpdateContactResponse) => void): grpc.ClientUnaryCall;
    /**
     * Deletes a contact with the provided id.
     *
     * @generated from protobuf rpc: DeleteContact(proto.contacts.v1.DeleteContactRequest) returns (google.protobuf.Empty);
     */
    deleteContact(input: DeleteContactRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Empty) => void): grpc.ClientUnaryCall;
    deleteContact(input: DeleteContactRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Empty) => void): grpc.ClientUnaryCall;
    deleteContact(input: DeleteContactRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Empty) => void): grpc.ClientUnaryCall;
    deleteContact(input: DeleteContactRequest, callback: (err: grpc.ServiceError | null, value?: Empty) => void): grpc.ClientUnaryCall;
    /**
     * Creates a contact.
     *
     * @generated from protobuf rpc: CreateContact(proto.contacts.v1.CreateContactRequest) returns (proto.contacts.v1.CreateContactResponse);
     */
    createContact(input: CreateContactRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: CreateContactResponse) => void): grpc.ClientUnaryCall;
    createContact(input: CreateContactRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: CreateContactResponse) => void): grpc.ClientUnaryCall;
    createContact(input: CreateContactRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: CreateContactResponse) => void): grpc.ClientUnaryCall;
    createContact(input: CreateContactRequest, callback: (err: grpc.ServiceError | null, value?: CreateContactResponse) => void): grpc.ClientUnaryCall;
}
/**
 * An API for managing a collection of contacts.
 *
 * @generated from protobuf service proto.contacts.v1.ContactsService
 */
export class ContactsServiceClient extends grpc.Client implements IContactsServiceClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * List all available contacts.
     *
     * @generated from protobuf rpc: ListContacts(proto.contacts.v1.ListContactsRequest) returns (proto.contacts.v1.ListContactsResponse);
     */
    listContacts(input: ListContactsRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: ListContactsResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: ListContactsResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: ListContactsResponse) => void)): grpc.ClientUnaryCall {
        const method = ContactsService.methods[0];
        return this.makeUnaryRequest<ListContactsRequest, ListContactsResponse>(`/${ContactsService.typeName}/${method.name}`, (value: ListContactsRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): ListContactsResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * Retrieves a specific contact.
     *
     * @generated from protobuf rpc: GetContact(proto.contacts.v1.GetContactRequest) returns (proto.contacts.v1.GetContactResponse);
     */
    getContact(input: GetContactRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetContactResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetContactResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GetContactResponse) => void)): grpc.ClientUnaryCall {
        const method = ContactsService.methods[1];
        return this.makeUnaryRequest<GetContactRequest, GetContactResponse>(`/${ContactsService.typeName}/${method.name}`, (value: GetContactRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GetContactResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * Updates a contact with the provided information.
     *
     * @generated from protobuf rpc: UpdateContact(proto.contacts.v1.UpdateContactRequest) returns (proto.contacts.v1.UpdateContactResponse);
     */
    updateContact(input: UpdateContactRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: UpdateContactResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: UpdateContactResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: UpdateContactResponse) => void)): grpc.ClientUnaryCall {
        const method = ContactsService.methods[2];
        return this.makeUnaryRequest<UpdateContactRequest, UpdateContactResponse>(`/${ContactsService.typeName}/${method.name}`, (value: UpdateContactRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): UpdateContactResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * Deletes a contact with the provided id.
     *
     * @generated from protobuf rpc: DeleteContact(proto.contacts.v1.DeleteContactRequest) returns (google.protobuf.Empty);
     */
    deleteContact(input: DeleteContactRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Empty) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Empty) => void), callback?: ((err: grpc.ServiceError | null, value?: Empty) => void)): grpc.ClientUnaryCall {
        const method = ContactsService.methods[3];
        return this.makeUnaryRequest<DeleteContactRequest, Empty>(`/${ContactsService.typeName}/${method.name}`, (value: DeleteContactRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): Empty => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * Creates a contact.
     *
     * @generated from protobuf rpc: CreateContact(proto.contacts.v1.CreateContactRequest) returns (proto.contacts.v1.CreateContactResponse);
     */
    createContact(input: CreateContactRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: CreateContactResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: CreateContactResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: CreateContactResponse) => void)): grpc.ClientUnaryCall {
        const method = ContactsService.methods[4];
        return this.makeUnaryRequest<CreateContactRequest, CreateContactResponse>(`/${ContactsService.typeName}/${method.name}`, (value: CreateContactRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): CreateContactResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
}
